version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: devuser
      WORDPRESS_DB_PASSWORD: devpwd
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./html:/var/www/html

  db:
    image: mariadb:10
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpwd
      MYSQL_DATABASE: wpdb
    volumes:
      - ./data/db:/var/lib/mysql
